on:
    push:
      branches:
        - main
    workflow_dispatch:
    repository_dispatch:
      types:
        - deploy
        - build-deploy
        - production-deploy
  
name: 🚀 Deploy website
jobs:
    build:
      name: 🔨 Build
      runs-on: ubuntu-latest
      steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v3
  
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '22'
        
        - name: Install dependencies
          run: npm install
          
        - name: Build project
          run: npm run build
          
        - name: Copy .htaccess to dist
          run: |
            cp .htaccess dist/        
          
        - name: Upload build artifacts
          uses: actions/upload-artifact@v4
          with:
            name: build-output
            path: ./dist
  
    deploy:
      name: 📂 Deploy
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v4
          with:
            name: build-output
            path: ./dist
  
        - name: Deploy to FTP
          uses: SamKirkland/FTP-Deploy-Action@v4.3.5
          with:
            server: ${{ secrets.server }}
            username: ${{ secrets.username }}
            password: ${{ secrets.password }}
            local-dir: ./dist/
            server-dir: ${{ secrets.server_dir }}